// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package rest_v1

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson8e4821bfDecodeGithubComMorphcloudOauth2ServerInternalHandlersHttpRestV1(in *jlexer.Lexer, out *UserCreds) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "login":
			out.Login = string(in.String())
		case "password":
			out.Password = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8e4821bfEncodeGithubComMorphcloudOauth2ServerInternalHandlersHttpRestV1(out *jwriter.Writer, in UserCreds) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"login\":"
		out.RawString(prefix[1:])
		out.String(string(in.Login))
	}
	{
		const prefix string = ",\"password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserCreds) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8e4821bfEncodeGithubComMorphcloudOauth2ServerInternalHandlersHttpRestV1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserCreds) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8e4821bfEncodeGithubComMorphcloudOauth2ServerInternalHandlersHttpRestV1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserCreds) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8e4821bfDecodeGithubComMorphcloudOauth2ServerInternalHandlersHttpRestV1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserCreds) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8e4821bfDecodeGithubComMorphcloudOauth2ServerInternalHandlersHttpRestV1(l, v)
}
func easyjson8e4821bfDecodeGithubComMorphcloudOauth2ServerInternalHandlersHttpRestV11(in *jlexer.Lexer, out *LoginResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "tokenType":
			out.TokenType = string(in.String())
		case "accessToken":
			out.AccessToken = string(in.String())
		case "accessTokenExpiresIn":
			out.AccessTokenExpiresIn = int64(in.Int64())
		case "refreshToken":
			out.RefreshToken = string(in.String())
		case "refreshTokenExpiresIn":
			out.RefreshTokenExpiresIn = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8e4821bfEncodeGithubComMorphcloudOauth2ServerInternalHandlersHttpRestV11(out *jwriter.Writer, in LoginResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"tokenType\":"
		out.RawString(prefix[1:])
		out.String(string(in.TokenType))
	}
	{
		const prefix string = ",\"accessToken\":"
		out.RawString(prefix)
		out.String(string(in.AccessToken))
	}
	{
		const prefix string = ",\"accessTokenExpiresIn\":"
		out.RawString(prefix)
		out.Int64(int64(in.AccessTokenExpiresIn))
	}
	{
		const prefix string = ",\"refreshToken\":"
		out.RawString(prefix)
		out.String(string(in.RefreshToken))
	}
	{
		const prefix string = ",\"refreshTokenExpiresIn\":"
		out.RawString(prefix)
		out.Int64(int64(in.RefreshTokenExpiresIn))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v LoginResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8e4821bfEncodeGithubComMorphcloudOauth2ServerInternalHandlersHttpRestV11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v LoginResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8e4821bfEncodeGithubComMorphcloudOauth2ServerInternalHandlersHttpRestV11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *LoginResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8e4821bfDecodeGithubComMorphcloudOauth2ServerInternalHandlersHttpRestV11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *LoginResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8e4821bfDecodeGithubComMorphcloudOauth2ServerInternalHandlersHttpRestV11(l, v)
}
